### ISSUE TITLE
Copy Mean to Mid Function from EEMS v2.0 TWS Fork to EEMS v 3.0

### ISSUE THREAD

**Issue by johngallo** [consbio/mpilot#1]
It is the normalizing function known as "Mean to Mid .  it is highlighted in this fork: https://github.com/consbio/EEMS/tree/TWSAndExplorer 

What it does: It provides an automated approach to creating a non-linear transformation that matched the data fairly well.  It essentially automates what we do when we do a convert-to-fuzzy-curve .  If you are converting a set of numbers to range from 0-1, the mean ov those numbers becomes a 0.5.  The mean of the top half of numbers becomes a 0.75.  and so on. I believe the logic is documented, Tim's long term vision is to make a "Transformations library" and add this in, among others, like quantiles.  (Quantiles may negate the need for this one, but that is a side discussion.)

simple example, a dataset that is highly skewed to the left, ranges from 0-1000, with a few outliers near 1000, but the mean value is 1.  The normalize function if used to range from 0-1, would give a value of 1000 a new value of 1, and the mean value of 1 a new value of 0.001 .   Instead, this function Will give the value of 100 a 1, that stays the same, but it gives the input value of 1 an output value of 0.5 instead of 0.001.

The output looks similar as quantiles.  If there is a function out there for quantiles, it may be better and more accepted to use that instead.  Since this one is written, maybe use this one for now and plan on replacing with quantiles at some point?

**Comment by nikmolnar** [comment]
This is also used by multiple EEMS models in Data Basin, and so will need to be supported before upgrading Data Basin to support MPilot.
