### ISSUE TITLE
CvtToFuzzyMeanToMid Not Working

### ISSUE THREAD

**Issue by zcanter** [consbio/mpilot#3]
Using EEMS3.0 downloaded from loxodonta

![image](https://user-images.githubusercontent.com/5613001/110530450-4e967180-80cf-11eb-95af-a3b999103261.png)

![image](https://user-images.githubusercontent.com/5613001/110530360-34f52a00-80cf-11eb-9230-e8b86c05cee1.png)

**Comment by nikmolnar** [comment]
As @mikegough mentioned via email, this issue would be better served at https://github.com/consbio/EEMS3-for-ArcGIS.
