### ISSUE TITLE
Consider changing MeanToMid() to CvtToFuzzyMeanToMid()

### ISSUE THREAD

**Issue by mikegough** [consbio/mpilot#4]
The MeanToMid operator converts raw data to fuzzy data, similar to how the other "Convert to Fuzzy Operators" work (e.g.,  CvtToFuzzyCurve, CvtToFuzzyCurveZScore, CvtToFuzzyCat, etc). 

For consistency, I think we should change the name of this operator from MeanToMid() to CvtToFuzzyMeanToMid()

https://github.com/consbio/mpilot/blob/9d830eee5b61b23e66eff006af61b9432c778fc8/mpilot/libraries/eems/fuzzy.py#L216

Both **EEMS3.0 for ArcGIS** and **EEMS Online**  call the operator CvtToFuzzyMeanToMid(), so currently uploads will fail if a model contains a MeanToMid() operator.

**Comment by johngallo** [comment]
Sounds good to me!

**Comment by nikmolnar** [comment]
Fixed in `1.0.0b18`.
