### ISSUE TITLE
Prevent the use of non-fuzzy operators on fuzzy values

### ISSUE THREAD

**Issue by mikegough** [consbio/mpilot#5]
Previous versions of EEMS would prevent the user from using fuzzy operators (e.g. SUM, MEAN, DIVIDE, MULTIPLY, etc) on fuzzy data.  Using a non-fuzzy operator on fuzzy data has the potential to produce values that fall outside of fuzzy space. Doing this invalidates the model.  The model validation step should trigger an error when the user attempts this.  Since EEMS Online uses a previous version of MPilot, it won't allow users to upload a model that uses a non-fuzzy operator on fuzzy data.

**Comment by nikmolnar** [comment]
Ok, I'm working through this issue, and am wondering if this should really be considered an error. While the current code allows fuzzy results to be used in non-fuzzy operations, the result _cannot_ then be used in a fuzzy function; it is in a sense "de-fuzzied".

It's this the more flexible option? To enforce fuzzy values where they're expected, and allow fuzzy values for "plain" functions, which in turn yield non-fuzzy results?

**Comment by johngallo** [comment]
I'm half listening to a webinar, but should jump in here asap. I do not think it is an error in all applications. MPILOT enables multi-criteria analysis.  One such analysis protocol is fuzzy logic. Another is weighted linear combination. There are others. In many (all?) of these you do a first step in which you normalize (transform) data into a single range of numeric values, such as -1 to 1, or 0 to 1.  we originally called this normalize step "convert to fuzzy" when really it shuodl have been "transform" or something like that. More coming in a bit.

**Comment by mikegough** [comment]
That's an interesting thought. I see your point. The model that triggered this conversation is sort of an anomaly in that the final output node is generated by a non-fuzzy operator (a WEIGHTED SUM).  Normally, the last node is the output from a fuzzy operator, so the rule that's currently in place would normally prevent this anyway.  Unless the user went from non-fuzzy -> fuzzy -> non-fuzzy operator -> back to fuzzy -> fuzzy operator. 

I guess I'm still inclined to say that only non-fuzzy values be allowed in non-fuzzy operators. Once you're in fuzzy space, you should not be able to jump back. If nothing else, then for compatibility with EEMS Online. Plus, in the words of the Godfather...

"_EEMS has operators designed to work on data before they are converted into fuzzy numerical space (i.e. when they are still in raw space) and those designed to work on data after they are converted into fuzzy space (see the above table). A user should respect that distinction._"

**Comment by johngallo** [comment]
I think the simple solution is for a warning be thrown when a non-fuzzy operator is performed on data that have been normalized, something like  "Warning: if you are attempting to implement fuzzy logic then this EEMS model is erroneous in that it uses non-fuzzy operators on fuzzy data, thereby allowing for values to fall outside of fuzzy space." 

Alternatively, there could be a click box or parameter that the user needs to click on or off for the question: are you using fuzzy logic?

**Comment by mikegough** [comment]
To be sure, there is a "Normalize" operator that you can use. This operator performs a linear transformation on the raw inputs, just like the "Convert to Fuzzy" does, but you can choose your "start value" and "end value" to be whatever you want (e.g., 0-1, or even -1 to +1). The output from this conversion CAN be used in non-fuzzy operator.

**Comment by mikegough** [comment]
I think this is opening the flood gates for a wave of invalid models. If users are able to create large complex models using fuzzy-logic throughout, and then they are allowed to do a WEIGHTED SUM at the top to add together, say, three fuzzy values, that's a huge problem. You're going to end up with a multitude of EEMS models with values of 3, 10, 100, etc as a final output. 

MPilot allows for multi-criteria analysis of various forms....

...but EEMS is a fuzzy logic modeling system, and the rules of fuzzy logic should be enforced.

**Comment by nikmolnar** [comment]
So EEMS models always have to end in fuzzy space?

**Comment by nikmolnar** [comment]
What I mean is even with the current restrictions, someone could end their EEMS model with a `CvtFromFuzzy` and you could end up with final outputs of 3, 10, 100, etc. Are you saying those would be invalid?

**Comment by mikegough** [comment]
I wouldn't say it's invalid, per se, but the output from an EEMS Fuzzy Logic Model is a value that indicates how true or false a proposition is. A value of +1 indicates the proposition is totally TRUE, and a value of -1 indicates that the proposition is totally FALSE. Numbers outside of this domain have no meaning on the truth continuum. So, even though technically speaking, it would be allowed under the rules of EEMS, if you pointed to your output and said "here are the results of my EEMS fuzzy logic model", I'd say something went horribly wrong.

**Comment by nikmolnar** [comment]
Thanks, @mikegough. I will move forward with the original plan of making it an error to pass fuzzy results to non-fuzzy functions. It sounds like there are other workarounds for John and Zac if they want do use it differently.

**Comment by nikmolnar** [comment]
I wonder, though: does `CvtFromFuzzy` have any realistic use in an EEMS model?

**Comment by zcanter** [comment]
I think this could be solved by creating a set of normalization tools that handle non-fuzzy approaches (i.e. normalize, which is already there). Basically, that would turn CvtToFuzzyCat to NormalizeCat or something like that, and CvtToFuzMeanToMid to just MeanToMid. The only thing holding EEMS back from a non-fuzzy approach is the normalization tools (I think).

**Comment by mikegough** [comment]
Yeah, the thought had occurred to me. It would address the issue. I'm pretty sure this is how the Normalize tool and MeanToMid tools ended up there in the first place. These tools were originally created for the EEMS-TWS version of EEMS. 

I would just caution against using EEMS for something it was never intended for.

**Comment by zcanter** [comment]
Yeah, that makes sense. I think John is pretty clear that he wants to go this route though. Perhaps we could just get a NormalizeCategory tool or something? That would fix everything for us I think.

**Comment by nikmolnar** [comment]
This is fixed in `1.0.0b19`
